apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
  interval: 10m
  retryInterval: 1m
  path: ./infrastructure/networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
