---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: isambard-values
  namespace: flux-system
spec:
  encryptedData:
    values.yaml: AgCpzq5YrUy+GyHvfkYonQJ/CkmNpWZ1hp/pLoHNwd46u32jdyrdhBsGU9f8hedo7mZhETIrAYy+o8BlNDhZqzCWpoviWv68wXEinsf1zot9S/S3o/KvkdhcWTMnWhXzWSyeNGd/FYsHSO6Gle3DtVxluaK+GDdqIF0MKdQIpG/XYxKsDVpm5NNp1xmqJDQlVfuCkKSJQGdGV4O1eRGj9M6AfnRJ0PFOPJBy9ZeqFfLZP4aB6WV+Nk7SsLYe4FghDCtLk4aWWE9+pBvBD7oFj4m8/MWQ+vQ3T50vfQFz2NsuYFORsoOnRJCA6DVS8DgqGCs7EdkuTou8AJvevAr7I8lhlMjrV2Ip5CWwtYzhru6qSKikZV5OrIrRcaUkFQosHQTkCZhqcrsCADMsrn7jF3PWqzc3RQuPT9rj4oAGHsItstUo1ekhJLluuDhsOaTOkP9W/64Cx1yXnci+VVkfKvxziNAFGSjAcT6OLb+b2+p1puKE8pJqado0cT8ChTVyhrd2/3zKtR14Jlz34EEBcuhC8AoJVCYoRC2XbfyV5S5L/kZp/dsF5wnfhGFGqvrn51scJSfAQ8QyhqVrtSZ2zRNmjNEqZFb5+B6G6WTLRP8+sbqAjldrvrRodGtDoqgDinMf8GwrYagDRZM3JwNvIyF5TiK2hd9tepkyV6j8pMjM5K2GNmLiXQojke3tXXsZi6H2489WfTu9+fc3L+jOr/OMDbMosDvUs8us28Iw2ctSXq202QFdLhiVHrO/k1VCh6jauTiOY0etPP4ZeLh8EqBeShnyNhNP8CzEBhcNDUjbJW5IJqR05UqnDeBNODNThWTl0nAeKaurqfmjtpBYiocJYc3XP1pOR7bZ1ppOoNaCLcUf/V5+
  template:
    metadata:
      name: isambard-values
      namespace: flux-system
