apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-certificates.yaml
  - pihole-ingress.yaml
  - jellyfin-pvc.yaml
  - jellyfin.yaml
  - isambard-sealedsecret.yaml
  - isambard.yaml
