networks:
  edge:
    driver: bridge

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: Europe/London
      FTLCONF_webserver_api_password: ${PIHOLE_WEB_PASSWORD}
      FTLCONF_dns_listeningMode: all
      FTLCONF_webserver_port: 8080o,[::]:8080o
      FTLCONF_misc_etc_dnsmasq_d: "true"
    volumes:
      - /srv/shared/vm/penzance/config/pihole:/etc/pihole
      - /srv/shared/vm/penzance/config/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080/tcp"
    networks:
      - edge
