apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: isambard
  namespace: media
spec:
  interval: 10m
  type: oci
  url: oci://forgejo.home.rpca.uk/ryan/charts
  secretRef:
    name: isambard-registry
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: isambard
  namespace: media
spec:
  interval: 10m
  timeout: 10m
  releaseName: isambard
  chart:
    spec:
      chart: isambard
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: isambard
        namespace: media
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: isambard
    image:
      repository: forgejo.home.rpca.uk/ryan/isambard
      tag: v0.1.8
      pullSecrets:
        - name: isambard-registry
    ingress:
      host: isambard.home.rpca.uk
      tls:
        secretName: media-home-rpca-uk-tls
    persistence:
      storageClass: homelab-local
      size: 10Gi
    media:
      hostPath: /mnt/crimson/media
      musicDir: /media/music
      moviesDir: /media/movies
      tvDir: /media/tv
      youtubeDir: /media/youtube
