---
- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart pihole container
  community.docker.docker_container:
    name: pihole
    restart: true
