all:
  children:
    proxmox_hosts:
      hosts:
        cornwall:
          ansible_host: 192.168.1.100
          ansible_user: root
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/cornwall_root_ed25519
    penzance:
      hosts:
        penzance:
          ansible_host: 192.168.1.101
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/penzance_automation_ed25519
          terraform_ssh_public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOBYMLaUpz08TKPKoGcRJX7gciqevrS1jkfaZt8gA4J7 ryan@penzance
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJc48QnL63S/DOz1knXAOVfqr5Umj6tTkBrp8HCMj6al automation@penzance
    k3s_control_plane:
      hosts:
        lyonesse-cp-01:
          ansible_host: 192.168.1.102
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/lyonesse-cp-01_automation_ed25519
          terraform_ssh_public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPd7xW7LPfnZpRWqHIXYDoxdZkzwD0QxA0Uhj6Ttgu5X ryan@lyonesse-cp-01
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOA1T2ekAkm6nSv/JV5avu1fKyf7U6vHnJ8CWp0cK9Pq automation@lyonesse-cp-01
    k3s_workers:
      hosts:
        lyonesse-w-01:
          ansible_host: 192.168.1.103
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/lyonesse-w-01_automation_ed25519
          terraform_ssh_public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHhHxR57EsiHZ+WEcAF+X3V9+Nc5Eqeel75wS2qTF+V4 ryan@lyonesse-w-01
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF7FTnpFyLnm50DxiENhJFQ3DlX1eEbzgv48OT8GMyXc automation@lyonesse-w-01
        lyonesse-w-02:
          ansible_host: 192.168.1.104
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/lyonesse-w-02_automation_ed25519
          terraform_ssh_public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILLoWwMqSiMLQS5rL0hxAV9HfffaT2zPd5O1dFas7bpK ryan@lyonesse-w-02
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE9ZJ4zI1Z8PzaAl0M0S/pA374CSr9WmfLZ1FvjZ3vaj automation@lyonesse-w-02
    k3s_cluster:
      children:
        k3s_control_plane: {}
        k3s_workers: {}
