all:
  children:
    proxmox_hosts:
      hosts:
        cornwall:
          ansible_host: 192.168.1.100
          ansible_user: root
          ansible_ssh_private_key_file: /tmp/homelab/ssh/cornwall_root_ed25519
          ssh_user: root
          ssh_private_key_file: /tmp/homelab/ssh/cornwall_root_ed25519
    penzance:
      hosts:
        penzance:
          ansible_host: 192.168.1.101
          ansible_ssh_private_key_file: /tmp/homelab/ssh/penzance_automation_ed25519
          ssh_user: ryan
          ssh_private_key_file: /tmp/homelab/ssh/penzance_ryan_ed25519
          terraform_ssh_public_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOBYMLaUpz08TKPKoGcRJX7gciqevrS1jkfaZt8gA4J7 ryan@penzance
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJc48QnL63S/DOz1knXAOVfqr5Umj6tTkBrp8HCMj6al automation@penzance
