all:
  children:
    proxmox_hosts:
      hosts:
        cornwall:
          ansible_host: 192.168.1.100
          ansible_user: root
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/cornwall_root_ed25519
    penzance:
      hosts:
        penzance:
          ansible_host: 192.168.1.101
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/penzance_automation_ed25519
          terraform_ssh_public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOBYMLaUpz08TKPKoGcRJX7gciqevrS1jkfaZt8gA4J7 ryan@penzance
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJc48QnL63S/DOz1knXAOVfqr5Umj6tTkBrp8HCMj6al automation@penzance
    k3s_control_plane:
      hosts:
        lyonesse-cp-01:
          ansible_host: 192.168.1.102
          ansible_ssh_private_key_file: /Users/ryan/Projects/k8s/keys/ssh/lyonesse-cp-01_automation_ed25519
          terraform_ssh_public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPd7xW7LPfnZpRWqHIXYDoxdZkzwD0QxA0Uhj6Ttgu5X ryan@lyonesse-cp-01
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOA1T2ekAkm6nSv/JV5avu1fKyf7U6vHnJ8CWp0cK9Pq automation@lyonesse-cp-01
    k3s_cluster:
      children:
        k3s_control_plane: {}
