---
- name: Configure k3s nodes
  hosts: k3s_cluster
  become: true
  vars_files:
    - ../inventories/lab/group_vars/all.secrets.yml
  roles:
    - common
    - k3s

- name: Install Cilium and Flux from control plane
  hosts: k3s_control_plane
  become: true
  vars_files:
    - ../inventories/lab/group_vars/all.secrets.yml
  roles:
    - cilium
    - flux
    - cluster_bootstrap
