apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
  namespace: ingress
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudflared-tunnel
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: cloudflare
        property: tunnel_token
