apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: isambard
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/towerundersiege/isambard.git
  ref:
    branch: main
