apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo
  namespace: forgejo
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - forgejo.home.rpca.uk
      secretName: forgejo-home-rpca-uk-tls
  rules:
    - host: forgejo.home.rpca.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo-http
                port:
                  number: 3000
