apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runner.yaml
  - runner.sops.yaml
  - admin.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingress.yaml
