apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "0.10.5"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://penzance:8200
      path: homelab
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: homelab
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
